### PR TITLE
Update select.emails querySelectorAll

### PR DESCRIPTION
**Pull request by beepidibop**
Gmail seems to have changed the class names where select.emails get emails from. This updates the class names queried so bundles work again

### CODE REVIEW

**Comment by jonrandy** [comment]
Might want to be careful here. I have one Gmail account where bundles are working right now, and one where it isn't

**Comment by beepidibop** [comment]
Ah, I might just be lucky enough that the class name changed on the two accounts I tested it on :P

**Comment by jonrandy** [comment]
I might take a look over the next few days and make it smart enough to deal with both - unless you want to do that first?

**Comment by beepidibop** [comment]
I've added the old class name back so it searches for both, hopefully this works. I tried testing the old class name but I don't have an account that still uses the old class name.

**Comment by joeytroy** [comment]
@beepidibop late to the party, I just tested this on all my accounts and it's not working for the bundles at all with your code.

**Comment by deepfriedfilth** [comment]
I've got bundling working by updating the selectors to [this](https://github.com/team-inbox/inbox-reborn/compare/master...deepfriedfilth:inbox-reborn:master)

**Comment by joeytroy** [comment]
@deepfriedfilth I'll try and spend some time on this tonight and push it up if it makes sense. Wonder if we shouldn't include the three different settings as it looks like Google is doing slow burn to update all users.

**Comment by jonrandy** [comment]
Not looked in any detail, but I have an inkling using `.bGI.nH[role=main]` might be more future-proof

**Comment by joeytroy** [comment]
@beepidibop @jonrandy @deepfriedfilth I am going to merge this in and also the fix from @deepfriedfilth as that one worked for me. @jonrandy I did try yours but it didn't work with my Google accounts but not to say it won't be one we add at a later time.

**Pull request merged**
