### PR TITLE
Contribution

### PR DESCRIPTION
**Pull request by shank-eric**
I forked the original repo about a year ago and converted to webpack among other modifications and have also been making adjustments for myself along the way.

### CODE REVIEW

**Comment by g60madman** [comment]
@shank-eric There are too many conflicts, it would be best to fork our work as a lot has been done to our main branch over boukestam's branch as we are 46 commits ahead of him. I don't want to work through the cleanup of code or changes we implemented since work on his branch stopped last year. I am going to close this out. I would recommend forking our main branch and implement your changes so we know they are not conflicting and submit them.

**Comment by shank-eric** [comment]
is it OK if I merge it into my branch instead and resolve the conflicts that way?

**Comment by g60madman** [comment]
That's just fine

**Comment by shank-eric** [comment]
I believe I have a successful merge to my develop branch, but I know this is a huge injection of code, so I've looked into creating a merge back with when I first did the webpack restructuring.  I merged inbox-reborn:master into this branch and that brings the changes way down: https://github.com/team-inbox/inbox-reborn/pull/24.  Thanks for the patience while I figure out how to get things integrated! 🙂

**Pull request closed without merging**
