### PR TITLE
Fixes side panel + floating button functionality + email bundling

### PR DESCRIPTION
**Pull request by deepfriedfilth**
By no surprise, Google made breaking changes affecting the extension.

..you'll want to update README with new version number / chrome link after merging and rolling out to chrome web store

### CODE REVIEW

**Comment by joeytroy** [comment]
@deepfriedfilth I am not seeing anything wrong, am I missing something? I have also tried the new version of Gmail and it still looks to be functioning properly. Let me know.

**Comment by jonrandy** [comment]
Having fixed the sidebar previously, I knew what to test... There does indeed seem to be a problem, although I haven't had time to test the fix. When opening and closing the sidebar for a 'Google' product (Keep, Calendar, Contacts, etc.) it works, but for third party sidebars (Todoist etc.) it is now broken.

**Comment by deepfriedfilth** [comment]
Just noticed the issue with third-party add-ons, I'll look into that and push a commit to address!

**Comment by deepfriedfilth** [comment]
@jonrandy after a lot of testing in both FF + Chrome, my latest commit should restore sidebar functionality for any add-on (Google or third-party) if you have a chance to test.

**Comment by deepfriedfilth** [comment]
Email bundling broke last week when Google changed the classes on the element used for grabbing a user's email address, which has been addressed with latest commit.

**Comment by jonrandy** [comment]
Will take a look (hopefully today) too. BTW - have you guys checked out https://app.shortwave.com/ ? Looks like a very promising Inbox clone

**Comment by jonrandy** [comment]
ok, just took a look... Email bundling, but sidebar is still not working at all - at least on Firefox

image

**Comment by deepfriedfilth** [comment]
@jonrandy re: side panel functionality, I did notice a slight lag on first use after a fresh page load in Firefox, which may be tied to [this waitForElement call](https://github.com/team-inbox/inbox-reborn/blob/master/src/script.js#L835) but after that initial hiccup it's been working as intended

**Comment by jonrandy** [comment]
Just tried again on a different machine as I'm at work now. Still doesn't work at all on Firefox or Chrome

**Comment by joeytroy** [comment]
@jonrandy are you using the new Gmail mode setting they are soon forcing? Everything was working fine on Windows 11 in Chrome for me using the new settings.

**Comment by jonrandy** [comment]
The new version was forced on me about a month ago

**Comment by deepfriedfilth** [comment]
Weird, I've tested in both browsers with the original and new Gmail "views" and save for the aforementioned FF bug, the buttons are making the appropriate moves

**Comment by jonrandy** [comment]
If I get time, will take a look this weekend - then we can compare notes

**Comment by jonrandy** [comment]
We have some other cosmetic fixes needed for the new GMail too

**Pull request merged**
