### PR TITLE
Team inbox integration

### PR DESCRIPTION
**Pull request by shank-eric**
reorganize into a webpack build based on https://github.com/samuelsimoes/chrome-extension-webpack-boilerplate

### CODE REVIEW

**Comment by g60madman** [comment]
@shank-eric there are still conflicts with the branch please resolve them before I look at merging it into the code. There are also some more updates I pulled in today as well from other developers.

**Comment by shank-eric** [comment]
thanks @g60madman , I merged master into my branch and the conflicts are resolved

**Comment by jonrandy** [comment]
Can I ask what the point is of adding webpack? Doesn't seem worth adding that extra tooling - I see no real benefit

**Comment by shank-eric** [comment]
I personally found the large single files hard to reason with and keep track of where the different parts were, so this was the first step I took when I forked the repo, followed up by splitting the large file into multiple smaller ones.  This first PR I'm just trying to apply the webpack structure without other significant changes to try to keep the it smaller for easier review.  I have several other changes/features that I was planning to incrementally integrate with additional PRs if this is accepted.

**Comment by jonrandy** [comment]
In my opinion, just splitting it into ES modules would seem a better route than going the whole hog and adding webpack. Too much tooling, complexity, and overhead - for no real benefit

**Comment by shank-eric** [comment]
ok

**Pull request closed without merging**
