### PR TITLE
Manifest V3 Extension

### PR DESCRIPTION
**Pull request by joeytroy**
Moving to version 3 of the manifest. Also pushing the version of our application to 1.0.0 and getting rid of the x.x.x.x versioning.

### CODE REVIEW

**Comment by joeytroy** [comment]
@jonrandy, @deepfriedfilth, @beepidibop,

If you could look over this commit to make sure it looks OK. I have verified it locally but want to make sure it looks good before we move to the new V3 Extension and it still works properly with Firefox which I have not tested. I updated it based on the Googles update to Manifest V3 https://developer.chrome.com/docs/extensions/develop/migrate along with updating the .js as well to support the newer `chrome.storage.local` over the older `localStorage`. If it looks good I will go ahead and merge it in.

**Comment by deepfriedfilth** [comment]
@joeytroy can't load the extension with manifest v3 changes in firefox as is, unfortunately. `background.service_worker` flag  would need to be enabled in about:config, which isn't ideal, ~although it appears you can disable "persistent" key in "background" node of manifest, but unsure if that's the ultimate solution.~ (nope, firefox still wouldn't install without re-adding `"scripts": ["src/background.js"]` in addition to `service_worker` entry, and Chrome web store will most likely reject it for having both, according to some users in the GH issue linked below)

Some relevant reading:
- [Mozilla web-ext repo issue](https://github.com/mozilla/web-ext/issues/2532)
- [Mozilla Extension Workshop docs](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/#event-driven-background-scripts)
- [MDN Background_scripts entry](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Background_scripts)

**Comment by joeytroy** [comment]
@deepfriedfilth thanks for looking into that we may need to create a new branch just for Firefox users.

@jonrandy would you be willing to keep up with a Firefox branch since you uploaded the newest version of the extension? Since Google is forcing us to manifest 3 not sure we are going to have a choice unless we can figure out how to implement Firefox and Chrome compatibility into the manifest 3.

**Comment by jonrandy** [comment]
So, if I'm reading correctly, both can use manifest v3 but Firefox requires an extra line in the manifest that will cause it to be rejected in Chrome store?

**Comment by joeytroy** [comment]
@jonrandy that sounds correct I have not yet looked at the shared links that @deepfriedfilth posted.

**Comment by jonrandy** [comment]
Just had a quick read through those links and [this](https://github.com/mozilla/web-ext/issues/2532#issuecomment-1657258201) seems to be the quickest solution

**Comment by deepfriedfilth** [comment]
@jonrandy (unrelated) when you have a moment, could you upload the latest "release" (v.0.5.9.31) via Mozilla Add-Ons?

It terms of this manifest v3 cross-browser compatibility snafu, I've seen some solutions that employ build tooling to output the appropriate manifest or other differences for browser-specific versions.. unsure about the Chrome Web Store, but I believe Mozilla will make you jump through more hoops in verification if we adapt things to utilize task runner/automation solutions (I know they specifically mention webpack when uploading an add-on to their portal, but any pre-processing would apply)

**Comment by joeytroy** [comment]
@deepfriedfilth @jonrandy so I merged the code and have submitted the code to the Chrome store and we are now at version 1.0.0 to start us fresh with updates. We can create a Fork called Firefox or add a new repository for Firefox since Manifest 3 is causing issues. Let me know how to proceed with that. Also, not sure how much time it's worth spending on Firefox as we only have 11 Firefox users compared to 720 users in the Chrome Store. I leave that decision up to you all.

**Comment by jonrandy** [comment]
Am kinda super busy with work and a bunch of other projects, so I think the best plan sounds like waiting on this to see if there is any demand for further fixes.

I've pretty much abandoned the GMail interface in favour of Shortwave for personal mail, so that user count is likely down to 10

**Comment by deepfriedfilth** [comment]
@jonrandy thanks for your contributions to the project over the years, but I totally get moving on to that new new.

I know you're keeping busy but would you mind adding me as an author via Mozilla Add-Ons so I could at least upload the latest compatible version (v0.5.9.31) for the few fellow Firefox users? I've been submitting an unlisted version myself but would love to make my latest chat related fixes available to anyone who may be interested.

I wouldn't mind diving in and seeing how to move forward using manifest v3 and maintaining a FF version!

**Comment by jonrandy** [comment]
@deepfriedfilth Done!

**Pull request merged**
