### PR TITLE
Adds Priority Inbox Headings option + fixes avatars within bundles

### LINKED ISSUE #81: Avatars not working
it just shows a white circle
I think I saw the avatars when I just enabled the extension a day ago but now it doesn't work
I've tried in incognito mode, still the same

### PR DESCRIPTION
**Pull request by deepfriedfilth**
- Adds "Hide Priority Inbox Headings" option to hide these headings on desktop for a cleaner experience, really only affects users who have the "Priority Inbox" option selected in Settings > Inbox > Inbox type (provides more focused browsing, especially in mobile app)
- Adds green header color for Chat views
- Adds red header color for Meet views
- Fixes #81 
- A little bit of general cleanup

Tested on latest versions of Firefox + Chrome

### CODE REVIEW

**Comment by joeytroy** [comment]
@deepfriedfilth I'll look at this tonight and merge and submit to the chrome store.

**Comment by deepfriedfilth** [comment]
Cool. Couple more minor cosmetic tweaks rolled in this afternoon as well!

**Comment by deepfriedfilth** [comment]
@jonrandy could you pull + update on mozilla add-ons when you have a moment?

**Comment by jonrandy** [comment]
Done - https://addons.mozilla.org/en-GB/firefox/addon/inbox-reborn-theme-gmail/

**Comment by joeytroy** [comment]
@deepfriedfilth @jonrandy I updated the readme with the new info on version.

**Pull request merged**
