### PR TITLE
Fix Compose button, Pull in boukestam updates

### PR DESCRIPTION
**Pull request by jeff-hykin**
Take a look at the commits for detailed changes

### CODE REVIEW

**Comment by jeff-hykin** [comment]
@g60madman thanks for the access! Did you want them on a PR, a feature branch, or just master?

**Comment by g60madman** [comment]
@jeff-hykin Just slap into master would be great! Thanks for helping with the project, I want to get it released back out into the store soon just was working on fixing the new bug and saw you knocked it out so figure we need you on the project 👍

**Comment by jeff-hykin** [comment]
Thanks for merging it. I attempted yesterday, but I don't think I had permission to, and I think I still don't. I started looking into it, but had to take care of some other things yesterday.

**Comment by g60madman** [comment]
@jeff-hykin you bet! I am working on submitting it back to Google as well for the Chrome store. I am hoping to have that completed soon.

**Pull request merged**
